"""Kokoro TTS service controller."""

from fastapi import HTTPException

from app.models.schemas import TTSRequest
from app.services.tts_client import KokoroClientError, KokoroTTSClient


class TTSController:
    """Controller for text-to-speech operations using Kokoro TTS."""

    def __init__(self, tts_client: KokoroTTSClient) -> None:
        """Initialize the controller with a Kokoro TTS client."""
        self.tts_client = tts_client

    async def generate_speech(self, request: TTSRequest) -> bytes:
        """
        Process a text-to-speech request.

        Args:
            request: TTS request payload

        Returns:
            Raw audio bytes generated by Kokoro TTS.

        Raises:
            HTTPException: If the Kokoro TTS call fails.
        """
        try:
            return await self.tts_client.synthesize_speech(request)
        except KokoroClientError as exc:
            raise HTTPException(
                status_code=exc.status_code or 502,
                detail=exc.details or str(exc),
            ) from exc


