"""TTS service controller (Kokoro + ElevenLabs)."""

from fastapi import HTTPException

from app.models.schemas import TTSRequest
from app.services.eleven_client import ElevenLabsClientError, ElevenLabsTTSClient
from app.services.tts_client import KokoroClientError, KokoroTTSClient


class TTSController:
    """Controller for text-to-speech operations using multiple providers."""

    def __init__(
        self,
        kokoro_client: KokoroTTSClient,
        eleven_client: ElevenLabsTTSClient | None = None,
    ) -> None:
        """Initialize the controller with Kokoro and optional ElevenLabs clients."""
        self.kokoro_client = kokoro_client
        self.eleven_client = eleven_client

    async def generate_speech(self, request: TTSRequest) -> bytes:
        """
        Process a text-to-speech request.

        Args:
            request: TTS request payload

        Returns:
            Raw audio bytes generated by the selected TTS provider.

        Raises:
            HTTPException: If the TTS call fails or provider is misconfigured.
        """
        try:
            if request.provider == "elevenlabs":
                if self.eleven_client is None:
                    raise HTTPException(
                        status_code=500,
                        detail="ElevenLabs TTS is not configured. Set ELEVENLABS_API_KEY in the environment.",
                    )
                return await self.eleven_client.synthesize_speech(request)

            # Default provider: Kokoro
            return await self.kokoro_client.synthesize_speech(request)

        except (KokoroClientError, ElevenLabsClientError) as exc:
            # Custom client errors: wrap into HTTPException with appropriate status code if available
            status_code = getattr(exc, "status_code", None) or 502
            details = getattr(exc, "details", None) or str(exc)
            raise HTTPException(status_code=status_code, detail=details) from exc

